Fix db_dump build issue with some older toolchain
With some older gcc toolchain, mosquitto_db_dump fails to build because of
missing link with -lrt

[2021-04-13T08:09:44.016Z] time_mosq.o: In function `mosquitto_time':
[2021-04-13T08:09:44.016Z] /home/jenkins/workspace/CORE/Builder/slave_g/network/lib_mosquitto/apps/db_dump/../../lib/time_mosq.c:44: undefined reference to `clock_gettime'
[2021-04-13T08:09:44.016Z] collect2: ld returned 1 exit status
[2021-04-13T08:09:44.016Z] make[6]: *** [Makefile:28: mosquitto_db_dump] Error 1